### ISSUE TITLE
What can I do on the source code or reference to make this software support win7 64bit?

### ISSUE THREAD

**Issue by windofxy** [xuhao1/FOXTracker#14]
I tried running this software without camera plugging in ,UI and setting seemed fine.
but when i plugged camera in and ran the software, i found that camera's output looked like the old television and then crashed.
Do you have any ideas to help me solve this problem? THX XD

**Comment by windofxy** [comment]
以下是上面说明的中文版本
当我在没有插入摄像头的时候运行软件，窗口和软件设置都工作正常
当我插入摄像头运行软件时，软件内摄像头输出窗口显示着带花屏的黑白画面，1秒后软件停止工作
我觉得是软件负责获取摄像头画面信息的部分出了问题
你有什么好的解决方案吗，多谢

**Comment by windofxy** [comment]
附加
我下午测试了一下你第三方库的那个[aitracker](https://github.com/AIRLegend/aitrack)，发现这个软件可以在Win7 64bit正常运行，可能你的程序对这块地方做了什么改动？能否回答下，多谢XD

**Comment by windofxy** [comment]
不过试了试感觉aitracker的延迟很高，准确率也不太好，你的软件是我用过效果最好的，我想试试能不能让它兼容win7 64bit

**Comment by xuhao1** [comment]
不支持Win7 也不会去做支持，时间成本太高。
The realse of this software not support Win7 x64, it works on Win 10 x64 only.
