### ISSUE TITLE
希望摇杆热键能解绑

### ISSUE THREAD

**Issue by hjf222289** [xuhao1/FOXTracker#5]
现在Hotkeys只能绑定不能解绑，希望增加在绑定窗口按Esc键或其他按键解绑的功能

**Comment by xuhao1** [comment]
> 现在Hotkeys只能绑定不能解绑，希望增加在绑定窗口按Esc键或其他按键解绑的功能

以后会加，现在直接改config.yaml即可

**Comment by xuhao1** [comment]
The unbind button is added in version 0.1.0
新的0.1.0版本已经加入了解绑按键。
